set(vtkalglib_LOADED 1)
set(vtkalglib_DEPENDS "")
set(vtkalglib_LIBRARIES "vtkalglib")
set(vtkalglib_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/ThirdParty/alglib;/home/urf/Documents/VTK-7.1.1/ThirdParty/alglib")
set(vtkalglib_LIBRARY_DIRS "")
set(vtkalglib_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtkalglib_WRAP_HIERARCHY_FILE "")
set(vtkalglib_KIT "")
set(vtkalglib_EXCLUDE_FROM_WRAPPING 1)

