set(vtkexpat_LOADED 1)
set(vtkexpat_DEPENDS "")
set(vtkexpat_LIBRARIES "vtkexpat")
set(vtkexpat_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/ThirdParty/expat;/home/urf/Documents/VTK-7.1.1/ThirdParty/expat")
set(vtkexpat_LIBRARY_DIRS "")
set(vtkexpat_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtkexpat_WRAP_HIERARCHY_FILE "")
set(vtkexpat_KIT "")
set(vtkexpat_EXCLUDE_FROM_WRAPPING 1)

