set(vtkInteractionStyle_LOADED 1)
set(vtkInteractionStyle_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMath;vtkCommonTransforms;vtkFiltersExtraction;vtkFiltersSources;vtkRenderingCore;vtkRenderingCore")
set(vtkInteractionStyle_LIBRARIES "vtkInteractionStyle")
set(vtkInteractionStyle_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/Interaction/Style;/home/urf/Documents/VTK-7.1.1/Interaction/Style")
set(vtkInteractionStyle_LIBRARY_DIRS "")
set(vtkInteractionStyle_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtkInteractionStyle_WRAP_HIERARCHY_FILE "")
set(vtkInteractionStyle_KIT "vtkInteraction")
set(vtkInteractionStyle_IMPLEMENTS "vtkRenderingCore")

