set(vtkkwiml_LOADED 1)
set(vtkkwiml_DEPENDS "")
set(vtkkwiml_LIBRARIES "")
set(vtkkwiml_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/Utilities/KWIML;/home/urf/Documents/VTK-7.1.1/Utilities/KWIML")
set(vtkkwiml_LIBRARY_DIRS "")
set(vtkkwiml_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtkkwiml_WRAP_HIERARCHY_FILE "")
set(vtkkwiml_KIT "")
set(vtkkwiml_EXCLUDE_FROM_WRAPPING 1)

