set(vtkMetaIO_LOADED 1)
set(vtkMetaIO_DEPENDS "vtkzlib")
set(vtkMetaIO_LIBRARIES "vtkmetaio")
set(vtkMetaIO_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/Utilities/MetaIO/vtkmetaio;/home/urf/Documents/VTK-7.1.1/VTK-build/Utilities/MetaIO;/home/urf/Documents/VTK-7.1.1/Utilities/MetaIO")
set(vtkMetaIO_LIBRARY_DIRS "")
set(vtkMetaIO_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtkMetaIO_WRAP_HIERARCHY_FILE "")
set(vtkMetaIO_KIT "")
set(vtkMetaIO_EXCLUDE_FROM_WRAPPING 1)

