set(vtknetcdf_LOADED 1)
set(vtknetcdf_DEPENDS "vtkhdf5")
set(vtknetcdf_LIBRARIES "vtkNetCDF;vtkNetCDF_cxx")
set(vtknetcdf_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/ThirdParty/netcdf/vtknetcdf/include;/home/urf/Documents/VTK-7.1.1/VTK-build/ThirdParty/netcdf/vtknetcdf;/home/urf/Documents/VTK-7.1.1/VTK-build/ThirdParty/netcdf;/home/urf/Documents/VTK-7.1.1/ThirdParty/netcdf")
set(vtknetcdf_LIBRARY_DIRS "")
set(vtknetcdf_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtknetcdf_WRAP_HIERARCHY_FILE "")
set(vtknetcdf_KIT "")
set(vtknetcdf_EXCLUDE_FROM_WRAPPING 1)

