set(vtkParseOGLExt_LOADED 1)
set(vtkParseOGLExt_DEPENDS "")
set(vtkParseOGLExt_LIBRARIES "")
set(vtkParseOGLExt_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/Utilities/ParseOGLExt;/home/urf/Documents/VTK-7.1.1/Utilities/ParseOGLExt")
set(vtkParseOGLExt_LIBRARY_DIRS "")
set(vtkParseOGLExt_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtkParseOGLExt_WRAP_HIERARCHY_FILE "")
set(vtkParseOGLExt_KIT "")
set(vtkParseOGLExt_EXCLUDE_FROM_WRAPPING 1)

