set(vtkRenderingContextOpenGL_HEADERS_LOADED 1)
set(vtkRenderingContextOpenGL_HEADERS "vtkOpenGLContextActor;vtkOpenGL2ContextDevice2D;vtkOpenGLContextBufferId;vtkOpenGLContextDevice2D;vtkOpenGLContextDevice3D;vtkOpenGLPropItem;vtkRenderingContextOpenGLObjectFactory")

foreach(header ${vtkRenderingContextOpenGL_HEADERS})
  set(vtkRenderingContextOpenGL_HEADER_${header}_EXISTS 1)
endforeach()


set(vtkRenderingContextOpenGL_HEADER_vtkOpenGL2ContextDevice2D_WRAP_EXCLUDE 1)
set(vtkRenderingContextOpenGL_HEADER_vtkOpenGLContextBufferId_WRAP_EXCLUDE 1)
set(vtkRenderingContextOpenGL_HEADER_vtkOpenGLContextDevice2D_WRAP_EXCLUDE 1)
set(vtkRenderingContextOpenGL_HEADER_vtkOpenGLContextDevice3D_WRAP_EXCLUDE 1)
set(vtkRenderingContextOpenGL_HEADER_vtkOpenGLPropItem_WRAP_EXCLUDE 1)
set(vtkRenderingContextOpenGL_HEADER_vtkRenderingContextOpenGLObjectFactory_WRAP_EXCLUDE 1)

set(vtkRenderingContextOpenGL_HEADER_vtkRenderingContextOpenGLObjectFactory_WRAP_EXCLUDE_PYTHON 1)

