set(vtkRenderingVolumeOpenGL_LOADED 1)
set(vtkRenderingVolumeOpenGL_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMath;vtkCommonSystem;vtkCommonTransforms;vtkFiltersCore;vtkFiltersGeneral;vtkFiltersGeometry;vtkFiltersSources;vtkImagingCore;vtkRenderingCore;vtkRenderingOpenGL;vtkRenderingVolume;vtkRenderingVolume;vtksys")
set(vtkRenderingVolumeOpenGL_LIBRARIES "vtkRenderingVolumeOpenGL")
set(vtkRenderingVolumeOpenGL_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/Rendering/VolumeOpenGL;/home/urf/Documents/VTK-7.1.1/Rendering/VolumeOpenGL")
set(vtkRenderingVolumeOpenGL_LIBRARY_DIRS "")
set(vtkRenderingVolumeOpenGL_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtkRenderingVolumeOpenGL_WRAP_HIERARCHY_FILE "")
set(vtkRenderingVolumeOpenGL_KIT "vtkOpenGL")
set(vtkRenderingVolumeOpenGL_IMPLEMENTS "vtkRenderingVolume")

