set(vtkRenderingFreeType_LOADED 1)
set(vtkRenderingFreeType_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkFiltersGeneral;vtkRenderingCore;vtkRenderingCore;vtkfreetype")
set(vtkRenderingFreeType_LIBRARIES "vtkRenderingFreeType")
set(vtkRenderingFreeType_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/Rendering/FreeType;/home/urf/Documents/VTK-7.1.1/Rendering/FreeType")
set(vtkRenderingFreeType_LIBRARY_DIRS "")
set(vtkRenderingFreeType_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtkRenderingFreeType_WRAP_HIERARCHY_FILE "")
set(vtkRenderingFreeType_KIT "vtkRendering")
set(vtkRenderingFreeType_IMPLEMENTS "vtkRenderingCore")

