set(vtksqlite_LOADED 1)
set(vtksqlite_DEPENDS "")
set(vtksqlite_LIBRARIES "vtksqlite")
set(vtksqlite_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/ThirdParty/sqlite;/home/urf/Documents/VTK-7.1.1/ThirdParty/sqlite")
set(vtksqlite_LIBRARY_DIRS "")
set(vtksqlite_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtksqlite_WRAP_HIERARCHY_FILE "")
set(vtksqlite_KIT "")
set(vtksqlite_EXCLUDE_FROM_WRAPPING 1)

