set(vtktiff_LOADED 1)
set(vtktiff_DEPENDS "vtkjpeg;vtkzlib")
set(vtktiff_LIBRARIES "vtktiff")
set(vtktiff_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/ThirdParty/tiff/vtktiff/libtiff;/home/urf/Documents/VTK-7.1.1/VTK-build/ThirdParty/tiff;/home/urf/Documents/VTK-7.1.1/ThirdParty/tiff")
set(vtktiff_LIBRARY_DIRS "")
set(vtktiff_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtktiff_WRAP_HIERARCHY_FILE "")
set(vtktiff_KIT "")
set(vtktiff_EXCLUDE_FROM_WRAPPING 1)

