set(vtkzlib_LOADED 1)
set(vtkzlib_DEPENDS "")
set(vtkzlib_LIBRARIES "vtkzlib")
set(vtkzlib_INCLUDE_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/ThirdParty/zlib;/home/urf/Documents/VTK-7.1.1/ThirdParty/zlib")
set(vtkzlib_LIBRARY_DIRS "")
set(vtkzlib_RUNTIME_LIBRARY_DIRS "/home/urf/Documents/VTK-7.1.1/VTK-build/lib")
set(vtkzlib_WRAP_HIERARCHY_FILE "")
set(vtkzlib_KIT "")
set(vtkzlib_EXCLUDE_FROM_WRAPPING 1)

